# Generated by Django 4.0.5 on 2022-06-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('regDate', models.DateField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
